// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MojStomatolog.Database;

#nullable disable

namespace MojStomatolog.Database.Migrations
{
    [DbContext(typeof(MojStomatologContext))]
    partial class MojStomatologContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MojStomatolog.Models.Core.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"), 1L, 1);

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Procedure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            AppointmentDateTime = new DateTime(2024, 2, 2, 14, 30, 0, 0, DateTimeKind.Local),
                            IsConfirmed = true,
                            Notes = "",
                            PatientId = 1,
                            Procedure = "Skidanje kamenca"
                        },
                        new
                        {
                            AppointmentId = 2,
                            AppointmentDateTime = new DateTime(2024, 2, 3, 14, 30, 0, 0, DateTimeKind.Local),
                            IsConfirmed = true,
                            Notes = "",
                            PatientId = 1,
                            Procedure = "Pregled"
                        },
                        new
                        {
                            AppointmentId = 3,
                            AppointmentDateTime = new DateTime(2024, 2, 2, 11, 30, 0, 0, DateTimeKind.Local),
                            IsConfirmed = true,
                            Notes = "",
                            PatientId = 2,
                            Procedure = "Skidanje kamenca"
                        },
                        new
                        {
                            AppointmentId = 4,
                            AppointmentDateTime = new DateTime(2024, 2, 2, 10, 30, 0, 0, DateTimeKind.Local),
                            IsConfirmed = true,
                            Notes = "",
                            PatientId = 3,
                            Procedure = "Popravak zuba"
                        },
                        new
                        {
                            AppointmentId = 5,
                            AppointmentDateTime = new DateTime(2024, 2, 3, 11, 30, 0, 0, DateTimeKind.Local),
                            IsConfirmed = true,
                            Notes = "",
                            PatientId = 2,
                            Procedure = "Pregled"
                        });
                });

            modelBuilder.Entity("MojStomatolog.Models.Core.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArticleId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            Content = "Redoviti posjeti stomatologu ključni su za očuvanje oralnog zdravlja. Stomatolog će pregledati vaše zube, desni i ukazati na potencijalne probleme prije nego što postanu ozbiljni.",
                            PublishDate = new DateTime(2024, 2, 2, 18, 28, 56, 971, DateTimeKind.Local).AddTicks(2268),
                            Summary = "Očuvanje oralnog zdravlja kroz redovite posjete stomatologu.",
                            Title = "Važnost Redovitih Pregleda Kod Stomatologa"
                        },
                        new
                        {
                            ArticleId = 2,
                            Content = "Pravilna tehnika četkanja zuba ključna je za sprječavanje karijesa i bolesti desni. Obratite pažnju na pritisak, kut četkanja i koristite kvalitetnu četkicu za zube.",
                            PublishDate = new DateTime(2024, 2, 2, 18, 28, 56, 971, DateTimeKind.Local).AddTicks(2277),
                            Summary = "Savjeti za postizanje savršene tehnike četkanja zuba.",
                            Title = "Pravilno Četkanje Zuba: Kako Postići Savršenu Tehniku"
                        },
                        new
                        {
                            ArticleId = 3,
                            Content = "Vaša ishrana igra ključnu ulogu u održavanju zdravlja vaših zuba. Ograničite unos šećera, konzumirajte mliječne proizvode i voće te pijte dovoljno vode za optimalnu oralnu hidrataciju.",
                            PublishDate = new DateTime(2024, 2, 2, 18, 28, 56, 971, DateTimeKind.Local).AddTicks(2314),
                            Summary = "Kako ishrana utječe na zdravlje zuba i desni.",
                            Title = "Zdrava Ishrana za Zdrave Zube"
                        },
                        new
                        {
                            ArticleId = 4,
                            Content = "Estetski zahvati poput izbjeljivanja zuba, keramičkih faseta i ortodontskih tretmana mogu poboljšati izgled vašeg osmijeha. Posavjetujte se sa stomatologom o opcijama prilagođenim vašim potrebama.",
                            PublishDate = new DateTime(2024, 2, 2, 18, 28, 56, 971, DateTimeKind.Local).AddTicks(2328),
                            Summary = "Pregled estetskih zahvata za ljepši osmijeh.",
                            Title = "Estetski Zahvati u Stomatologiji: Sve Što Trebate Znati"
                        });
                });

            modelBuilder.Entity("MojStomatolog.Models.Core.CompanySetting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingId"), 1L, 1);

                    b.Property<string>("SettingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SettingId");

                    b.ToTable("CompanySettings");

                    b.HasData(
                        new
                        {
                            SettingId = 1,
                            SettingName = "WorkingHours",
                            SettingValue = "08:30-18:00"
                        });
                });

            modelBuilder.Entity("MojStomatolog.Models.Core.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Email = "ahmedahmedic@mojstomatolog.ba",
                            FirstName = "Ahmed",
                            Gender = "M",
                            LastName = "Ahmedic",
                            Number = "123456789",
                            Specialization = "Stomatolog",
                            StartDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = 2,
                            Email = "lejlalejlic@mojstomatolog.ba",
                            FirstName = "Lejla",
                            Gender = "F",
                            LastName = "Lejlic",
                            Number = "987654321",
                            Specialization = "Asistent",
                            StartDate = new DateTime(2023, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = 3,
                            Email = "adnanadnanic@mojstomatolog.ba",
                            FirstName = "Adnan",
                            Gender = "M",
                            LastName = "Adnanic",
                            Number = "555666777",
                            Specialization = "Higijeničar",
                            StartDate = new DateTime(2023, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = 4,
                            Email = "aminaaminic@mojstomatolog.ba",
                            FirstName = "Amina",
                            Gender = "F",
                            LastName = "Aminic",
                            Number = "111222333",
                            Specialization = "Stomatolog",
                            StartDate = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = 5,
                            Email = "harisharisic@mojstomatolog.ba",
                            FirstName = "Haris",
                            Gender = "M",
                            LastName = "Harisic",
                            Number = "444555666",
                            Specialization = "Asistent",
                            StartDate = new DateTime(2023, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MojStomatolog.Models.Core.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 29.30m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderDate = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 24.10m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            OrderDate = new DateTime(2023, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 19.80m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            OrderDate = new DateTime(2023, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 32.10m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            OrderDate = new DateTime(2023, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 32.21m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            OrderDate = new DateTime(2023, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 24.80m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            OrderDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 15.95m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            OrderDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 27.10m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            OrderDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 40.26m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            OrderDate = new DateTime(2023, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 15.00m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            OrderDate = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 19.80m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            OrderDate = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 33.25m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            OrderDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 20.41m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            OrderDate = new DateTime(2023, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 23.10m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 15,
                            OrderDate = new DateTime(2023, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 28.45m,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("MojStomatolog.Models.Core.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            Price = 7.50m,
                            ProductId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            Price = 3.60m,
                            ProductId = 6,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 1,
                            Price = 10.70m,
                            ProductId = 11,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            Price = 9.90m,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 2,
                            Price = 4.95m,
                            ProductId = 7,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 2,
                            Price = 9.25m,
                            ProductId = 12,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 3,
                            Price = 9.90m,
                            ProductId = 3,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 4,
                            Price = 7.15m,
                            ProductId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 4,
                            Price = 8.50m,
                            ProductId = 8,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 10,
                            OrderId = 4,
                            Price = 7.95m,
                            ProductId = 15,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 11,
                            OrderId = 5,
                            Price = 7.65m,
                            ProductId = 5,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 12,
                            OrderId = 5,
                            Price = 6.96m,
                            ProductId = 9,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 13,
                            OrderId = 5,
                            Price = 9.95m,
                            ProductId = 13,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 14,
                            OrderId = 6,
                            Price = 12.40m,
                            ProductId = 10,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 15,
                            OrderId = 7,
                            Price = 7.40m,
                            ProductId = 14,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 16,
                            OrderId = 7,
                            Price = 4.95m,
                            ProductId = 7,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 17,
                            OrderId = 7,
                            Price = 3.60m,
                            ProductId = 6,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 18,
                            OrderId = 8,
                            Price = 9.25m,
                            ProductId = 12,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 19,
                            OrderId = 8,
                            Price = 9.90m,
                            ProductId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 20,
                            OrderId = 8,
                            Price = 7.95m,
                            ProductId = 15,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 21,
                            OrderId = 9,
                            Price = 12.40m,
                            ProductId = 10,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 22,
                            OrderId = 9,
                            Price = 6.96m,
                            ProductId = 9,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 23,
                            OrderId = 9,
                            Price = 8.50m,
                            ProductId = 8,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 24,
                            OrderId = 10,
                            Price = 7.50m,
                            ProductId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 25,
                            OrderId = 11,
                            Price = 9.90m,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 26,
                            OrderId = 11,
                            Price = 9.90m,
                            ProductId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 27,
                            OrderId = 12,
                            Price = 7.15m,
                            ProductId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 28,
                            OrderId = 12,
                            Price = 7.65m,
                            ProductId = 5,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 29,
                            OrderId = 12,
                            Price = 3.60m,
                            ProductId = 6,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 30,
                            OrderId = 13,
                            Price = 4.95m,
                            ProductId = 7,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 31,
                            OrderId = 13,
                            Price = 8.50m,
                            ProductId = 8,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 32,
                            OrderId = 13,
                            Price = 6.96m,
                            ProductId = 9,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 33,
                            OrderId = 14,
                            Price = 12.40m,
                            ProductId = 10,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 34,
                            OrderId = 14,
                            Price = 10.70m,
                            ProductId = 11,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 35,
                            OrderId = 15,
                            Price = 9.25m,
                            ProductId = 12,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 36,
                            OrderId = 15,
                            Price = 9.95m,
                            ProductId = 13,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("MojStomatolog.Models.Core.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Active = true,
                            Description = "Colgate 360 Max White medium četkica za zube, odlična je za čišćenje zuba, jezika, obraza i desni. Zahvaljujući jedinstvenim spiralnim vlaknima pomažu u izbjeljivanju zuba, uklanjanju površinskih mrlja i čišćenju čak i teško dostupnih mjesta. Osim toga, čistač jezika na stražnjoj strani četkice efikasno i nježno uklanja bakterije koje uzrokuju loš zadah. Obogatite oralnu higijenu uz Colgate 360 Max white četkicu za zube!",
                            ImageUrl = "https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1699963147/products/pim/5900273125941_P1_BG/colgate-360-max-white-cetkica-za-zube-medium",
                            Name = "Colgate 360 Max White Medium",
                            Price = 7.5,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            Active = true,
                            Description = "Curaprox CS 1560 Soft četkica za zube sa finim Curen vlaknima pruža temeljno čišćenje zuba. Zahvaljujući posebno tankim vlaknima od 0,15 mm, četkica dopire do teško dostupnih međuzubnih prostora i sprječava nastanak naslaga, karijesa i umanjuje nastanak upale zubnog mesa. Zahvaljujući maloj kompaktnoj glavi i osmerostrukom držaču osigurava jednostavno rukovanje i kvalitetnije četkanje zuba. Curaprox CS 1560 Soft četkica za zube – vaše desni i zubi će vam biti zahvalni!",
                            ImageUrl = "https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1699840608/products/pim/7612412156003-3069130/curaprox-soft-1560-cetkica-za-zube-vise-vrsta",
                            Name = "Curaprox CS 1560 Soft",
                            Price = 9.9000000000000004,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            Active = true,
                            Description = "Curaprox CS 5460 Ultra Soft četkica za zube sa finim Curen vlaknima pruža temeljno čišćenje zuba. Zahvaljujući posebno tankim vlaknima od 0,1 mm, četkica dopire do teško dostupnih međuzubnih prostora i sprječava nastanak naslaga, karijesa i umanjuje nastanak upale zubnog mesa. Zahvaljujući maloj kompaktnoj glavi i osmerostrukom držaču osigurava jednostavno rukovanje i kvalitetnije četkanje zuba. Curaprox CS 5460 Ultra Soft četkica za zube – vaše desni i zubi će vam biti zahvalni!",
                            ImageUrl = "https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1699840603/products/pim/7612412423143-3059572/curaprox-ultra-soft-5460-cetkica-za-zube-vise-vrsta",
                            Name = "Curaprox Ultra Soft 5460",
                            Price = 9.9000000000000004,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            Active = true,
                            Description = "Sensodyne četkica za zube - medium, posebno je dizajnirana za osobe s osjetljivim desnima i zubima. Četkicu za zube odlikuje poseban i funkcionalan dizajn, jer sa mekim vanjskim vlaknima i zaobljenim unutrašnjim vlaknima nježno, ali učinkovito čisti zubnu caklinu, vaše desni i osjetljiva područja, a istovremeno temeljno uklanja zubne naslage. Praktična mala glava četkice dopire do teško dostupnih mjesta i omogućava temeljno čišćenje. Sensodyne četkica za zube - za savršenu oralnu njegu!",
                            ImageUrl = "https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1700030477/products/pim/3830029296118-2367466/sensodyne-cetkica-za-zube-medium",
                            Name = "Sensodyne Medium",
                            Price = 7.1500000000000004,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            Active = true,
                            Description = "Elmex Ultra soft četkica za zube zahvaljujući specijalno dizajniranim svilenkastim vlaknima pruža nježno ali temeljno čišćenje zuba. Posebno oblikovana glava četkice za zube dopiru do teško dostupnih mjesta i međuzubnih prostora i tako sprječavaju nastanak naslaga i karijesa. Osim toga, svilenkasta vlakna četkice osim što temeljno čiste osiguravaju i ugodnu masažu desni. Elmex Ultra soft četkica za zube – za svršenu zubnu njegu.",
                            ImageUrl = "https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1700286070/products/pim/8718951187658_SK/elmex-ultra-soft-cetkica-za-zube-vise-vrsta",
                            Name = "Elmex Ultra Soft",
                            Price = 7.6500000000000004,
                            ProductCategoryId = 1
                        },
                        new
                        {
                            ProductId = 6,
                            Active = true,
                            Description = "Colgate MaxFresh Cool Blue pasta za zube, s osvježavajućim kristalima, nježno uklanja nečistoće i štiti zube od karijesa, naslaga i stvaranja zubnog kamenca. Osim toga, ima efekat izbjeljivanja te će vaši zubi biti za nijansu bjelji već nakon prvog pranja. Svjež dah će trajati i do 10 puta duže. Obogatite svoju svakodnevnu oralnu higijenu uz Colgate MaxFresh Cool Blue pastu za zube!",
                            ImageUrl = "https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1700279921/products/pim/8718951313576-2360918/colgate-max-fresh-pasta-za-zube-cooling-crystals",
                            Name = "Colgate Max Fresh",
                            Price = 3.6000000000000001,
                            ProductCategoryId = 2
                        },
                        new
                        {
                            ProductId = 7,
                            Active = true,
                            Description = "Aquafresh Triple Protection Fresh & Minty pasta za zube pruža trostruku zaštitu tokom 24h. Zahvaljujući formuli s fluoridom, pasta za zube efikasno čisti zube i štiti od karijesa i šećernih kiselina. Osim toga, osvježavajući okus mente dugotrajno osvježava i ostavlja svjež i ugodan dah. Redovnom upotrebom paste za zube jača se zubna caklina. Za zdrave zube i svjež dah uz Aquafresh Triple Protection Fresh & Minty pastu za zube.",
                            ImageUrl = "https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1700026010/products/pim/5999518578062-2360828/aquafresh-triple-protection-pasta-za-zube-fresh-minty",
                            Name = "Aquafresh Triple Protection Fresh & Minty",
                            Price = 4.9500000000000002,
                            ProductCategoryId = 2
                        },
                        new
                        {
                            ProductId = 8,
                            Active = true,
                            Description = "Elmex Anti Caries pasta za zube, s antibakterijskim djelovanje, nježno uklanja nečistoće i štiti zube od karijesa, naslaga i stvaranja zubnog kamenca. Zahvaljujući abrazivnom sredstvu, izbjeljuje zube i zubne vratove, vraća prirodnu boju i stvara zaštitni sloj koji štiti osjetljive zube i desni. Osim toga, svjež dah traje duže. Obogatite svoju svakodnevnu oralnu higijenu uz Elmex Anti Caries pastu za zube!",
                            ImageUrl = "https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1700315632/products/pim/8718951477575/elmex-anti-caries-pasta-za-zube",
                            Name = "Elmex Anti Caries",
                            Price = 8.5,
                            ProductCategoryId = 2
                        },
                        new
                        {
                            ProductId = 9,
                            Active = true,
                            Description = "Lacalut multi effect pasta za zube zahvaljujući aktivnim sastojcima osigurava idealnu zaštitu za sve zube. Hidroksiapatit i kalcij potiču remineralizaciju zubi i jačanje zubne cakline, zubi postaju glatkiji i otporniji. Fosfati sprječavaju stvaranje zubnog kamenca, rastvaraju naslage na zubima i ublažavaju mrlje. Kalcijev laktat i cink djeluju antibakterijski i antiseptički. Aluminijev laktat zateže i učvršćuje zubno meso te štiti od upale zubnog mesa izazvane bakterijama. Natrijev fluorid štiti od karijesa i potiče remineralizaciju zubi. Za zdrave desni i blistavo bijele zube - Lacalut multi effect pasta za zube!",
                            ImageUrl = "https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1699845196/products/pim/SK_4016369546246_B_P2/lacalut-multi-effect-pasta-za-zube",
                            Name = "Lacalut multi effect",
                            Price = 6.96,
                            ProductCategoryId = 2
                        },
                        new
                        {
                            ProductId = 10,
                            Active = true,
                            Description = "Sensodyne Complete Protection pasta za zube, s antibakterijskim djelovanjem, nježno uklanja nečistoće i štiti zube od stvaranja naslaga i zubnog kamenca. Osim toga, smanjuje osjetljivost zuba na toplo i hladno. Zahvaljujući aktivnoj formuli vraća prirodnu bjelinu zuba već nakon prvog pranja. Pomaže u jačanju zubne cakline i pruža dugotrajan osjećaj svježine u ustima. Obogatite svoju svakodnevnu oralnu higijenu uz Sensodyne Complete Protection pastu za zube!",
                            ImageUrl = "https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1699845113/products/pim/5054563119759_1/sensodyne-complete-protection-pasta-za-zube",
                            Name = "Sensodyne Complete Protection",
                            Price = 12.4,
                            ProductCategoryId = 2
                        },
                        new
                        {
                            ProductId = 11,
                            Active = true,
                            Description = "Listerine Total Care 6u1 antibakterijska vodica za ispiranje usta svojom efikasnom formulom sprječava nastanak zubnih naslaga i lošeg zadaha. Sa šesterostrukom zaštitom formulom bori se protiv bakterija, čak i na teško dostupnim mjestima u usnoj šupljini, gdje četkica za zube ne može doprijeti. Vodica za ispiranje usta pruža 12 sati zaštite od bakterija, jača caklinu, štiti od karijesa, smanjuje plak, štiti desni te osvježava dah. Listerine Total Care 6u1 antibakterijska vodica za ispiranje usta za blistavo bijele zube i intenzivno svjež dah!",
                            ImageUrl = "https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1700277825/products/pim/3574660415506-2351437/listerine-total-care-antibakterijska-vodica-za-ispiranje-usta",
                            Name = "Listerine Total Care",
                            Price = 10.699999999999999,
                            ProductCategoryId = 3
                        },
                        new
                        {
                            ProductId = 12,
                            Active = true,
                            Description = "Parodontax Active Care vodica za ispiranje usta pomaže u održavanju svakodnevne oralne higijene usne šupljine. Osim toga, vodica za ispiranje usta je ne sadrži alkohol, osvježava dah i djeluje antibakterijski i do 12 sat. Redovnom primjenom uklanja plak između desni i zuba, pomaže u sprečavanju ponavljajućih problema s desnima, dok je istovremeno nježan za desni. Klinički dokazano. Za osjećaj trenutne svježine i čistoće - Parodontax Active Care vodica za ispiranje usta!",
                            ImageUrl = "https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1700030464/products/pim/5054563052247-2367556/parodontax-active-care-vodica-za-ispiranje-usta",
                            Name = "Paradontax Active Care",
                            Price = 9.25,
                            ProductCategoryId = 3
                        },
                        new
                        {
                            ProductId = 13,
                            Active = true,
                            Description = "Lacalut Aktiv vodica za ispiranje usta pomaže u održavanju svakodnevne oralne higijene usne šupljine. Osim toga, vodica za ispiranje usta je ne sadrži alkohol, osvježava dah i djeluje antibakterijski i do 12 sat. Redovnom primjenom uklanja plak između desni i zuba, pomaže u sprečavanju ponavljajućih problema s desnima, dok je istovremeno nježan za desni. Klinički dokazano. Za osjećaj trenutne svježine i čistoće - Lacalut Aktiv vodica za ispiranje usta!",
                            ImageUrl = "https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1700202061/products/pim/4016369726297-2403956/lacalut-aktiv-vodica-za-ispiranje-usta",
                            Name = "Lacalut Aktiv",
                            Price = 9.9499999999999993,
                            ProductCategoryId = 3
                        },
                        new
                        {
                            ProductId = 14,
                            Active = true,
                            Description = "Colgate Cool Mint vodica za usta, pružit će svjež dah i zaštiti od bakterija. Vodica za ispiranje usta sa okusom mente ukloniti će bakterije koje nije moguće u potpunosti ukoniti samo četkanjem. Spriječit će stvaranje zubnog kamenca i karijesa. Obogatite oralnu higijenu uz Colgate Cool Mint vodicu za usta.",
                            ImageUrl = "https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1700273456/products/pim/8714789732671_cz/colgate-plax-vodica-za-ispiranje-usta-cool-mint",
                            Name = "Colgate Plax Cool Mint",
                            Price = 7.4000000000000004,
                            ProductCategoryId = 3
                        },
                        new
                        {
                            ProductId = 15,
                            Active = true,
                            Description = "Elmex Caries Protection vodica za usta, pružit će svjež dah i zaštiti od bakterija. Vodica za ispiranje uklonit će bakterije koje nije moguće u potpunosti odstraniti samo četkanjem. Spriječit će stvaranje zubnog kamenca i karijesa. Odlična je za osobe s ortodontskim aparatima i mostovima. Praktično pakovanje idealno je za putovanja ili situacije kada niste u prilici oprati zube. Obogatite oralnu higijenu uz Elmex Caries Protection vodicu za usta.",
                            ImageUrl = "https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1699839014/products/pim/7610108006878_SK/elmex-caries-protection-vodica-za-usta",
                            Name = "Elmex Caries Protection",
                            Price = 7.9500000000000002,
                            ProductCategoryId = 3
                        });
                });

            modelBuilder.Entity("MojStomatolog.Models.Core.ProductCategory", b =>
                {
                    b.Property<int>("ProductCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCategoryId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductCategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductCategoryId = 1,
                            Name = "četkica za zube"
                        },
                        new
                        {
                            ProductCategoryId = 2,
                            Name = "Pasta za zube"
                        },
                        new
                        {
                            ProductCategoryId = 3,
                            Name = "Vodica za ispiranje usta"
                        });
                });

            modelBuilder.Entity("MojStomatolog.Models.Core.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "mobiletest@mojstomatolog.ba",
                            FirstName = "Mobile",
                            LastName = "Test",
                            Number = "123456789",
                            PasswordHash = "eAgjVa5u+yP5GzGoMTpY0Sb5XowehZl3VNOjuUX8kJc=",
                            PasswordSalt = "2irDvagQHwn9bhLo7RopCA==",
                            Username = "mobile"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "adinisic@mojstomatolog.ba",
                            FirstName = "Adi",
                            LastName = "Nišić",
                            Number = "987654321",
                            PasswordHash = "eAgjVa5u+yP5GzGoMTpY0Sb5XowehZl3VNOjuUX8kJc=",
                            PasswordSalt = "2irDvagQHwn9bhLo7RopCA==",
                            Username = "adinisic"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "peroperic@mojstomatolog.ba",
                            FirstName = "Pero",
                            LastName = "Peric",
                            Number = "111222333",
                            PasswordHash = "eAgjVa5u+yP5GzGoMTpY0Sb5XowehZl3VNOjuUX8kJc=",
                            PasswordSalt = "2irDvagQHwn9bhLo7RopCA==",
                            Username = "peroperic"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "amaramaric@mojstomatolog.ba",
                            FirstName = "Amar",
                            LastName = "Amaric",
                            Number = "555444333",
                            PasswordHash = "eAgjVa5u+yP5GzGoMTpY0Sb5XowehZl3VNOjuUX8kJc=",
                            PasswordSalt = "2irDvagQHwn9bhLo7RopCA==",
                            Username = "amaramaric"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "aidaaidic@mojstomatolog.ba",
                            FirstName = "Aida",
                            LastName = "Aidic",
                            Number = "999888777",
                            PasswordHash = "eAgjVa5u+yP5GzGoMTpY0Sb5XowehZl3VNOjuUX8kJc=",
                            PasswordSalt = "2irDvagQHwn9bhLo7RopCA==",
                            Username = "aidaaidic"
                        },
                        new
                        {
                            UserId = 6,
                            Email = "desktoptest@mojstomatolog.ba",
                            FirstName = "Desktop",
                            LastName = "Test",
                            Number = "123789456",
                            PasswordHash = "eAgjVa5u+yP5GzGoMTpY0Sb5XowehZl3VNOjuUX8kJc=",
                            PasswordSalt = "2irDvagQHwn9bhLo7RopCA==",
                            Username = "desktop"
                        });
                });

            modelBuilder.Entity("Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RatingValue")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RatingId");

                    b.HasIndex("ProductId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            RatingId = 1,
                            ProductId = 1,
                            RatingValue = 4,
                            UserId = 1
                        },
                        new
                        {
                            RatingId = 2,
                            ProductId = 2,
                            RatingValue = 5,
                            UserId = 1
                        },
                        new
                        {
                            RatingId = 3,
                            ProductId = 3,
                            RatingValue = 3,
                            UserId = 1
                        },
                        new
                        {
                            RatingId = 4,
                            ProductId = 5,
                            RatingValue = 2,
                            UserId = 1
                        },
                        new
                        {
                            RatingId = 5,
                            ProductId = 3,
                            RatingValue = 4,
                            UserId = 2
                        },
                        new
                        {
                            RatingId = 6,
                            ProductId = 5,
                            RatingValue = 5,
                            UserId = 2
                        },
                        new
                        {
                            RatingId = 7,
                            ProductId = 6,
                            RatingValue = 5,
                            UserId = 2
                        },
                        new
                        {
                            RatingId = 8,
                            ProductId = 10,
                            RatingValue = 2,
                            UserId = 2
                        },
                        new
                        {
                            RatingId = 9,
                            ProductId = 14,
                            RatingValue = 4,
                            UserId = 2
                        },
                        new
                        {
                            RatingId = 10,
                            ProductId = 7,
                            RatingValue = 4,
                            UserId = 3
                        },
                        new
                        {
                            RatingId = 11,
                            ProductId = 4,
                            RatingValue = 4,
                            UserId = 3
                        },
                        new
                        {
                            RatingId = 12,
                            ProductId = 13,
                            RatingValue = 1,
                            UserId = 3
                        },
                        new
                        {
                            RatingId = 13,
                            ProductId = 12,
                            RatingValue = 5,
                            UserId = 3
                        },
                        new
                        {
                            RatingId = 14,
                            ProductId = 12,
                            RatingValue = 5,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("MojStomatolog.Models.Core.Appointment", b =>
                {
                    b.HasOne("MojStomatolog.Models.Core.User", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MojStomatolog.Models.Core.OrderItem", b =>
                {
                    b.HasOne("MojStomatolog.Models.Core.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MojStomatolog.Models.Core.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MojStomatolog.Models.Core.Product", b =>
                {
                    b.HasOne("MojStomatolog.Models.Core.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("Rating", b =>
                {
                    b.HasOne("MojStomatolog.Models.Core.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MojStomatolog.Models.Core.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
